# Generated by Django 3.2.4 on 2021-06-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['expired_at']},
        ),
        migrations.RunSQL("""
            INSERT INTO todo_category(name,image) VALUES
            ('Work','/static/images/work.png'),
            ('Home','/static/images/home.png'),
            ('Personal','/static/images/personal.png');
        """)
    ]
